# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cloud-task-manager-frontend-marcelina

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main_cloud-task-manager-frontend-marcelina.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_461EBCC2ADC54B9796D71772A74A509C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E08EDFE6FD1B42A98C0482772EC2CD1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9536733289124FFAAAC981CCAF76C27F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloud-task-manager-frontend-marcelina'
          slot-name: 'Production'
          package: ./frontend/dist